[project]
name = "rosalind"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "networkx>=3.5",
    "numpy>=2.3.3",
    "requests>=2.32.5",
    "scrapy>=2.13.4",
]
